# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               OK Computer
tagline:             'Yet another tech blog...'
description:         'Ici on parle essentiellement virualisation, stockage et OS mais pas que !'
url:                 http://blog.okcomputer.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              OK Computer
  url:               https://twitter.com/okcomputerpro
  email:             okcomputerpro@gmail.com
  github:            okcomputerpro

# Custom vars
version:             1.0.0
